In [1]:
import pandas as pd
import os
import dotenv
import ipaddress

dotenv.load_dotenv()

True

In [2]:
data_dir = os.getenv("DATA_DIR", './data')

# Data Loading

In [3]:
private_networks = [
    ipaddress.ip_network('192.168.0.0/16'),
    ipaddress.ip_network('10.0.0.0/8'),
    ipaddress.ip_network('172.16.0.0/12')
]

def is_private_ip(ip):
    ip = ipaddress.ip_address(ip)
    return any(ip in network for network in private_networks)

def load_df(filename, dirs):
    dirs.append(filename)
    label_flow_path = os.path.join(data_dir, *dirs)
    label_flow_df = pd.read_csv(label_flow_path)
    label_flow_df.columns = label_flow_df.columns.str.strip()
    return label_flow_df

def load_label_flow_df(filename):
    dirs = ['GeneratedLabelledFlows', 'TrafficLabelling']
    label_flow_df = load_df(filename, dirs)
    label_flow_df['Source IP is Private'] = label_flow_df['Source IP'].apply(is_private_ip)
    label_flow_df['Destination IP is Private'] = label_flow_df['Destination IP'].apply(is_private_ip)
    return label_flow_df

def load_ml_df(filename):
    dirs = ['MachineLearningCSV', 'MachineLearningCVE']
    return load_df(filename, dirs)

## This has to be done for all of these files

* Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
* Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
* Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
* Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
* Friday-WorkingHours-Morning.pcap_ISCX.csv
* Tuesday-WorkingHours.pcap_ISCX.csv
* Monday-WorkingHours.pcap_ISCX.csv
* Wednesday-workingHours.pcap_ISCX.csv

In [4]:
label_flow_df = load_label_flow_df('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
ml_df = load_ml_df('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')

# Data Exploration

## Label Flow

In [5]:
pd.set_option('display.max_columns', None)
label_flow_df.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Source IP is Private,Destination IP is Private
0,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.12,35396,192.168.10.50,22,6,7/7/2017 1:00,1266342,41,44,2664,6954,456,0,64.975610,109.864573,976,0,158.045455,312.675250,7595.104640,67.122468,15075.50000,104051.399700,948537.0,0.0,1266342.0,31658.550,159355.2595,996324.0,2.0,317671.0,7387.697674,19636.44809,104616.0,1.0,0,0,0,0,1328,1424,32.376720,34.745748,0,976,111.837209,239.686848,57449.78495,0,0,0,1,0,0,0,0,1,113.152941,64.975610,158.045455,1328,0,0,0,0,0,0,41,2664,44,6954,29200,243,24,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,True,True
1,192.168.10.16-192.168.10.50-60058-22-6,192.168.10.16,60058,192.168.10.50,22,6,7/7/2017 1:00,1319353,41,44,2664,6954,456,0,64.975610,109.864573,976,0,158.045455,312.675250,7289.936810,64.425518,15706.58333,104861.870100,955790.0,1.0,1319353.0,32983.825,159247.9008,996423.0,1.0,363429.0,8451.837209,21337.26261,104815.0,1.0,0,0,0,0,1328,1424,31.075838,33.349680,0,976,111.837209,239.686848,57449.78495,0,0,0,1,0,0,0,0,1,113.152941,64.975610,158.045455,1328,0,0,0,0,0,0,41,2664,44,6954,29200,243,24,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,True,True
2,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.12,35396,192.168.10.50,22,6,7/7/2017 1:00,160,1,1,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,12500.000000,160.00000,0.000000,160.0,160.0,0.0,0.000,0.0000,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0,0,0,0,32,32,6250.000000,6250.000000,0,0,0.000000,0.000000,0.00000,0,0,0,0,1,1,0,0,1,0.000000,0.000000,0.000000,32,0,0,0,0,0,0,1,0,1,0,290,243,0,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,True,True
3,192.168.10.12-192.168.10.50-35398-22-6,192.168.10.12,35398,192.168.10.50,22,6,7/7/2017 1:00,1303488,41,42,2728,6634,456,0,66.536585,110.129945,976,0,157.952381,319.121427,7182.267884,63.675308,15896.19512,106554.899000,956551.0,0.0,1303488.0,32587.200,160397.0499,997357.0,1.0,346851.0,8459.780488,23962.23892,138295.0,0.0,0,0,0,0,1328,1360,31.454068,32.221240,0,976,111.452381,241.642791,58391.23867,0,0,0,1,0,0,0,0,1,112.795181,66.536585,157.952381,1328,0,0,0,0,0,0,41,2728,42,6634,29200,243,24,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,True,True
4,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.50,22,192.168.10.12,35396,6,7/7/2017 1:00,77,1,2,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,38961.038960,38.50000,14.849242,49.0,28.0,0.0,0.000,0.0000,0.0,0.0,49.0,49.000000,0.00000,49.0,49.0,0,0,0,0,32,64,12987.012990,25974.025970,0,0,0.000000,0.000000,0.00000,0,0,0,0,1,1,0,0,2,0.000000,0.000000,0.000000,32,0,0,0,0,0,0,1,0,2,0,243,290,0,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,True,True

In [6]:
label_flow_df.shape

(286467, 87)

In [7]:
label_flow_df.info(max_cols = None)

<class 'pandas.DataFrame'>
RangeIndex: 286467 entries, 0 to 286466
Data columns (total 87 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Flow ID                      286467 non-null  str
 1   Source IP                    286467 non-null  str
 2   Source Port                  286467 non-null  int64
 3   Destination IP               286467 non-null  str
 4   Destination Port             286467 non-null  int64
 5   Protocol                     286467 non-null  int64
 6   Timestamp                    286467 non-null  str
 7   Flow Duration                286467 non-null  int64
 8   Total Fwd Packets            286467 non-null  int64
 9   Total Backward Packets       286467 non-null  int64
 10  Total Length of Fwd Packets  286467 non-null  int64
 11  Total Length of Bwd Packets  286467 non-null  int64
 12  Fwd Packet Length Max        286467 non-null  int64
 13  Fwd Packet Length Min        286467 non-null  int64
 14  Fwd Packet Length Mean       286467 non-null  float64
 15  Fwd Packet Length Std        286467 non-null  float64
 16  Bwd Packet Length Max        286467 non-null  int64
 17  Bwd Packet Length Min        286467 non-null  int64
 18  Bwd Packet Length Mean       286467 non-null  float64
 19  Bwd Packet Length Std        286467 non-null  float64
 20  Flow Bytes/s                 286452 non-null  float64
 21  Flow Packets/s               286467 non-null  float64
 22  Flow IAT Mean                286467 non-null  float64
 23  Flow IAT Std                 286467 non-null  float64
 24  Flow IAT Max                 286467 non-null  float64
 25  Flow IAT Min                 286467 non-null  float64
 26  Fwd IAT Total                286467 non-null  float64
 27  Fwd IAT Mean                 286467 non-null  float64
 28  Fwd IAT Std                  286467 non-null  float64
 29  Fwd IAT Max                  286467 non-null  float64
 30  Fwd IAT Min                  286467 non-null  float64
 31  Bwd IAT Total                286467 non-null  float64
 32  Bwd IAT Mean                 286467 non-null  float64
 33  Bwd IAT Std                  286467 non-null  float64
 34  Bwd IAT Max                  286467 non-null  float64
 35  Bwd IAT Min                  286467 non-null  float64
 36  Fwd PSH Flags                286467 non-null  int64
 37  Bwd PSH Flags                286467 non-null  int64
 38  Fwd URG Flags                286467 non-null  int64
 39  Bwd URG Flags                286467 non-null  int64
 40  Fwd Header Length            286467 non-null  int64
 41  Bwd Header Length            286467 non-null  int64
 42  Fwd Packets/s                286467 non-null  float64
 43  Bwd Packets/s                286467 non-null  float64
 44  Min Packet Length            286467 non-null  int64
 45  Max Packet Length            286467 non-null  int64
 46  Packet Length Mean           286467 non-null  float64
 47  Packet Length Std            286467 non-null  float64
 48  Packet Length Variance       286467 non-null  float64
 49  FIN Flag Count               286467 non-null  int64
 50  SYN Flag Count               286467 non-null  int64
 51  RST Flag Count               286467 non-null  int64
 52  PSH Flag Count               286467 non-null  int64
 53  ACK Flag Count               286467 non-null  int64
 54  URG Flag Count               286467 non-null  int64
 55  CWE Flag Count               286467 non-null  int64
 56  ECE Flag Count               286467 non-null  int64
 57  Down/Up Ratio                286467 non-null  int64
 58  Average Packet Size          286467 non-null  float64
 59  Avg Fwd Segment Size         286467 non-null  float64
 60  Avg Bwd Segment Size         286467 non-null  float64
 61  Fwd Header Length.1          286467 non-null  int64
 62  Fwd Avg Bytes/Bulk           286467 non-null  int64
 63  Fwd Avg Packets/Bulk         286467 non-null  int64
 64  Fwd Avg Bulk Rate            286467 non-null  int64
 65  Bwd Avg Bytes/Bulk           286467 non-null  int64
 66  Bwd Avg Packets/Bulk         286467 non-null  int64
 67  Bwd Avg Bulk Rate            286467 non-null  int64
 68  Subflow Fwd Packets          286467 non-null  int64
 69  Subflow Fwd Bytes            286467 non-null  int64
 70  Subflow Bwd Packets          286467 non-null  int64
 71  Subflow Bwd Bytes            286467 non-null  int64
 72  Init_Win_bytes_forward       286467 non-null  int64
 73  Init_Win_bytes_backward      286467 non-null  int64
 74  act_data_pkt_fwd             286467 non-null  int64
 75  min_seg_size_forward         286467 non-null  int64
 76  Active Mean                  286467 non-null  float64
 77  Active Std                   286467 non-null  float64
 78  Active Max                   286467 non-null  float64
 79  Active Min                   286467 non-null  float64
 80  Idle Mean                    286467 non-null  float64
 81  Idle Std                     286467 non-null  float64
 82  Idle Max                     286467 non-null  float64
 83  Idle Min                     286467 non-null  float64
 84  Label                        286467 non-null  str
 85  Source IP is Private         286467 non-null  bool
 86  Destination IP is Private    286467 non-null  bool
dtypes: bool(2), float64(36), int64(44), str(5)
memory usage: 186.3 MB

In [8]:
label_flow_df.describe()

/home/kilnaar/anaconda3/envs/data-exploration-cic-ids-2017/lib/python3.11/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/home/kilnaar/anaconda3/envs/data-exploration-cic-ids-2017/lib/python3.11/site-packages/pandas/core/nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,2.864520e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,286467.000000,286467.0,286467.0,286467.0,286467.000000,286467.000000,2.864670e+05,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.0,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.0,286467.0,286467.0,286467.0,286467.0,286467.0,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05
mean,43932.432563,8044.876324,8.306000,5.379331e+06,3.473283,3.520500,233.407667,2.707247e+03,81.033369,10.352013,24.138688,24.590994,185.649851,27.478530,76.473013,55.742307,inf,inf,3.435661e+05,6.690304e+05,1.821288e+06,1.152034e+04,5.255228e+06,7.790948e+05,5.086644e+05,1.773447e+06,4.483619e+05,4.968463e+06,7.972503e+05,3.961929e+05,1.569683e+06,5.053646e+05,0.020994,0.0,0.0,0.0,91.861527,87.156077,4.140927e+04,2.110817e+04,10.124908,206.783141,47.863395,61.756216,3.557227e+04,0.008692,0.020994,0.000073,0.660694,0.124116,0.044672,0.0,0.000073,0.850625,55.157954,24.138688,76.473013,91.861527,0.0,0.0,0.0,0.0,0.0,0.0,3.473283,233.407667,3.520500,2.707247e+03,11145.127076,1155.099977,1.728618,29.075328,3.409213e+04,2.294987e+04,7.785722e+04,2.171380e+04,1.602973e+06,6.120390e+04,1.647188e+06,1.536286e+06
std,17713.904328,15378.583442,4.481562,2.192364e+07,19.515131,28.288916,1865.523600,5.097783e+04,327.768035,24.237795,78.381542,117.218043,585.720606,54.209647,204.152865,196.643780,NaN,NaN,2.124999e+06,3.830433e+06,9.034294e+06,3.800536e+05,2.179685e+07,5.979401e+06,2.575708e+06,9.019385e+06,5.776419e+06,2.125371e+07,6.242734e+06,2.371670e+06,8.712596e+06,6.042689e+06,0.143363,0.0,0.0,0.0,503.560131,698.237440,1.601312e+05,6.246254e+04,18.768649,636.614018,122.031372,178.209296,1.631016e+05,0.092826,0.143363,0.008562,0.473475,0.329714,0.206583,0.0,0.008562,0.450208,129.794071,78.381542,204.152865,503.560131,0.0,0.0,0.0,0.0,0.0,0.0,19.515131,1865.523600,28.288916,5.097783e+04,14274.278654,6645.329412,14.897361,8.014607,4.659319e+05,2.623049e+05,7.342606e+05,4.223145e+05,8.682334e+06,1.217016e+06,8.882728e+06,8.561545e+06
min,0.000000,0.000000,0.000000,-1.300000e+01,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.930000e+08,-2.000000e+06,-1.300000e+01,0.000000e+00,-1.300000e+01,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,37516.000000,80.000000,6.000000,4.400000e+01,1.000000,1.000000,0.000000,6.000000e+00,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,6.000000,0.000000,7.928593e+03,1.664621e+02,4.400000e+01,0.000000e+00,4.400000e+01,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,24.000000,20.000000,8.374859e+01,3.291666e+01,0.000000,6.000000,2.000000,2.309401,5.333333e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,3.000000,0.000000,6.000000,24.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,6.000000e+00,237.000000,-1.000000,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,49008.000000,1110.000000,6.000000,6.500000e+01,1.000000,1.000000,2.000000,6.000000e+00,2.000000,2.000000,2.000000,0.000000,6.000000,6.000000,6.000000,0.000000,1.250000e+05,3.076923e+04,6.100000e+01,0.000000e+00,6.500000e+01,4.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,40.000000,20.000000,1.562500e+04,1.408451e+04,2.000000,6.000000,3.333333,3.464102,1.200000e+01,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,5.000000,2.000000,6.000000,40.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,2.000000,1.000000,6.000000e+00,1024.000000,0.000000,0.000000,24.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,56576.000000,6881.000000,6.000000,2.380600e+04,2.000000,2.000000,62.000000,1.150000e+02,37.000000,6.000000,34.000000,0.000000,72.000000,6.000000,66.000000,0.000000,1.904762e+05,4.545455e+04,7.986333e+03,8.602519e+01,2.368100e+04,6.300000e+01,4.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,3.000000e+00,2.000000e+00,1.666667e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000,0.0,0.0,0.0,44.000000,40.000000,2.272727e+04,2.272727e+04,6.000000,77.000000,53.000000,19.809359,3.924107e+02,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,67.166667,34.000000,66.000000,44.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,62.000000,2.000000,1.150000e+02,29200.000000,0.000000,1.000000,40.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65535.000000,65389.000000,17.000000,1.199999e+08,3119.000000,3635.000000,232349.000000,7.150819e+06,13929.000000,1472.000000,3412.938776,3541.466551,10136.000000,1460.000000,2442.523124,2628.883261,inf,inf,9.810000e+07,8.480000e+07,1.200000e+08,9.810000e+07,1.200000e+08,1.200000e+08,8.120000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.130000e+07,1.200000e+08,1.200000e+08,1.000000,0.0,0.0,0.0,79632.000000,81288.000000,3.000000e+06,2.000000e+06,289.000000,13929.000000,1588.000000,2497.019924,6.235109e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,124.000000,2068.000000,3412.938776,2442.523124,79632.000000,0.0,0.0,0.0,0.0,0.0,0.0,3119.000000,232349.000000,3635.000000,7.150819e+06,65535.000000,65535.000000,2056.000000,60.000000,1.100000e+08,7.050000e+07,1.100000e+08,1.100000e+08,1.200000e+08,7.050000e+07,1.200000e+08,1.200000e+08

In [9]:
label_flow_df['Label'].value_counts()

Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

In [10]:
label_flow_df['Source IP'].value_counts()

Source IP
172.16.0.1       158932
192.168.10.3      18226
192.168.10.14     13219
192.168.10.8      12384
192.168.10.15     11329
                  ...
52.20.22.149          1
52.204.60.8           1
52.204.148.49         1
23.203.64.44          1
34.205.210.59         1
Name: count, Length: 3667, dtype: int64

In [11]:
label_flow_df['Destination IP'].value_counts()

Destination IP
192.168.10.50      160716
192.168.10.3        41677
192.168.10.1        17983
192.168.10.14        2800
192.168.10.15        2498
                    ...
54.186.134.8            1
151.101.124.166         1
52.84.145.118           1
198.54.12.96            1
52.205.85.186           1
Name: count, Length: 4401, dtype: int64

In [12]:
label_flow_df['Source IP is Private'].value_counts()

Source IP is Private
True     267436
False     19031
Name: count, dtype: int64

In [13]:
label_flow_df['Destination IP is Private'].value_counts()

Destination IP is Private
True     241901
False     44566
Name: count, dtype: int64

In [14]:
label_flow_df['Source Port'].value_counts()

Source Port
443      13759
80        5201
60768     1009
59328     1009
55826     1004
         ...
21673        1
9366         1
9368         1
26359        1
1638         1
Name: count, Length: 36962, dtype: int64

In [15]:
label_flow_df['Destination Port'].value_counts()

Destination Port
53       58744
443      26935
80       16741
22         915
8080       778
         ...
8869         1
41864        1
8915         1
41888        1
9366         1
Name: count, Length: 14495, dtype: int64

## Machine Learning

In [16]:
pd.set_option('display.max_columns', None)
ml_df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,1266342,41,44,2664,6954,456,0,64.975610,109.864573,976,0,158.045455,312.675250,7595.104640,67.122468,15075.50000,104051.399700,948537,0,1266342,31658.550,159355.2595,996324,2,317671,7387.697674,19636.44809,104616,1,0,0,0,0,1328,1424,32.376720,34.745748,0,976,111.837209,239.686848,57449.78495,0,0,0,1,0,0,0,0,1,113.152941,64.975610,158.045455,1328,0,0,0,0,0,0,41,2664,44,6954,29200,243,24,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,22,1319353,41,44,2664,6954,456,0,64.975610,109.864573,976,0,158.045455,312.675250,7289.936810,64.425518,15706.58333,104861.870100,955790,1,1319353,32983.825,159247.9008,996423,1,363429,8451.837209,21337.26261,104815,1,0,0,0,0,1328,1424,31.075838,33.349680,0,976,111.837209,239.686848,57449.78495,0,0,0,1,0,0,0,0,1,113.152941,64.975610,158.045455,1328,0,0,0,0,0,0,41,2664,44,6954,29200,243,24,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,22,160,1,1,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,12500.000000,160.00000,0.000000,160,160,0,0.000,0.0000,0,0,0,0.000000,0.00000,0,0,0,0,0,0,32,32,6250.000000,6250.000000,0,0,0.000000,0.000000,0.00000,0,0,0,0,1,1,0,0,1,0.000000,0.000000,0.000000,32,0,0,0,0,0,0,1,0,1,0,290,243,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,22,1303488,41,42,2728,6634,456,0,66.536585,110.129945,976,0,157.952381,319.121427,7182.267884,63.675308,15896.19512,106554.899000,956551,0,1303488,32587.200,160397.0499,997357,1,346851,8459.780488,23962.23892,138295,0,0,0,0,0,1328,1360,31.454068,32.221240,0,976,111.452381,241.642791,58391.23867,0,0,0,1,0,0,0,0,1,112.795181,66.536585,157.952381,1328,0,0,0,0,0,0,41,2728,42,6634,29200,243,24,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,35396,77,1,2,0,0,0,0,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,38961.038960,38.50000,14.849242,49,28,0,0.000,0.0000,0,0,49,49.000000,0.00000,49,49,0,0,0,0,32,64,12987.012990,25974.025970,0,0,0.000000,0.000000,0.00000,0,0,0,0,1,1,0,0,2,0.000000,0.000000,0.000000,32,0,0,0,0,0,0,1,0,2,0,243,290,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [17]:
ml_df.shape

(286467, 79)